# -*- coding: utf-8 -*-
"""for_crawler.ipynb

Automatically generated by Colab.
"""


import requests # 請求存取頁面
from bs4 import BeautifulSoup

import pandas as pd
import numpy as np

URL = "https://www.khfv.com.tw/pagepub/AppContent.aspx?GP=GP04.01"

response = requests.get(URL)
soup = BeautifulSoup(response.text, "html.parser")

table = soup.find('table', id="WR1_1_WG1")

table

if table:

    header_row = table.find('tr', class_='CSS_AWG_Columns')
    if header_row:
        header_cells = header_row.find_all('td')
        column_headers = [cell.text.strip() for cell in header_cells]

        for i, header in enumerate(column_headers):
            print(f" {header}")

    else:
        print(" 找不到 class 為 'CSS_AWG_Columns' 的標題")

else:
    print(f"找不到 ID 為 '{table_id}' 的表格。")

Tbody = table.select('tr')
len(Tbody)

if table:
    all_rows = table.find_all('tr')

    table_data = []

    for i, row in enumerate(all_rows):


        # 在 tr 標籤下，找出所有的 td 或 th 標籤
        cells = row.find_all(['td', 'th'])

        # 提取每個 row 的文字，並清除前後的空白，形成一個列表
        row_content = [cell.text.strip() for cell in cells]

        # 每一行的數據加入到總數據列表中
        if row_content:
            table_data.append(row_content)

            # 判斷是否為標題行來印出更清晰的資訊
            is_header = 'class' in row.attrs and 'CSS_AWG_Columns' in row.attrs['class']
            row_type = "Header" if is_header else "Data"
            print(f"Index {i}: {row_content}")
else:
    print("找不到目標表格。")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

column_headers = table_data[0]
data_rows = table_data[1:]

df = pd.DataFrame(data_rows, columns=column_headers)
df

df.copy = df[['交易日期', '產品名稱','均價','交易量(公斤)']].copy()
df.copy

# 複製一份資料（這樣不會改到原始 df）
df_count = df.copy.copy()
target_rows = df_count[df_count['產品名稱'] == '包心白菜 包 白']
target_rows

# 移除千分位逗號再轉 float
df_count['交易量(公斤)'] = df_count['交易量(公斤)'].astype(str).str.replace(',', '', regex=False)
df_count['交易量(公斤)'] = pd.to_numeric(df_count['交易量(公斤)'], errors='coerce')

# 均價轉數字
df_count['均價'] = pd.to_numeric(df_count['均價'], errors='coerce')


# 加權平均
df_weighted = (
    df_count.groupby(['交易日期', '產品名稱'], as_index=False)
    .agg({
           '均價': lambda x: (x * df_count.loc[x.index, '交易量(公斤)']).sum() / df_count.loc[x.index, '交易量(公斤)'].sum(),
           '交易量(公斤)': 'sum'
       })
       .rename(columns={'均價': '加權平均價(元/公斤)', '交易量(公斤)': '總交易量(公斤)'})
 )
df_weighted['加權平均價(元/公斤)'] = df_weighted['加權平均價(元/公斤)'].round(6)
df_weighted.head()

df_weighted.to_csv('today_veg_prices.csv', index=False)

df_check= pd.read_csv('today_veg_prices.csv')
#df = df.drop(columns=['Unnamed: 0'])
df_check

df1 = pd.read_csv('veg_prices_history.csv')
df1

"""###這裡合併csv"""

import pandas as pd
df2 = df_check

# 上下合併
df_merged = pd.concat([df1, df2], ignore_index=True)

# 去除重複（假設以交易日期+產品名稱判斷）
df_merged.drop_duplicates(subset=['交易日期', '產品名稱'], keep='last', inplace=True)

df_merged.head()
len(df_merged)

# 將合併後的 DataFrame 存回 CSV 檔案，直接覆蓋
df_merged.to_csv('veg_prices_history.csv',float_format="%.6f", index=False)

print("合併後的資料已存回 veg_prices_history.csv")

df_cheeckmore = pd.read_csv('veg_prices_history.csv')
len(df_cheeckmore)

